from .heat_1d import Heat1D
from .heat_steady_2d import SteadyHeat2D
from .burgers_1d import BurgersRoe2
from .euler_1d import Euler1D
from .ns_channel_2d import NSChannel2D
from .ns_transient_2d import NSTransient2D
from .diff_react_1d import DiffReact1D
from .unstruct_mpm import UNSTRUCT_MPM
from .hasegawa_mima_linear import HasegawaMimaLinear
from .hasegawa_mima_nonlinear import HasegawaMimaNonlinear
