from .heat_1d import run_sim_heat_1d, get_res_heat_1d, compare_res_heat_1d
from .heat_steady_2d import run_sim_heat_steady_2d, get_res_heat_steady_2d, compare_res_heat_steady_2d
from .ns_channel_2d import run_sim_ns_channel_2d, get_res_ns_channel_2d, compare_res_ns_channel_2d
