project_name: costsci-tools
model:
  checkout:
    command: >- #copy shot+rho-specific input.cgyro into runners directory, then run checkout and push sim_res results to s3
      []() mkdir costsci-tools-cgyro/; mkdir costsci-tools-cgyro/<shot>/; mkdir costsci-tools-cgyro/<shot>/p<rho>/; cp data/<shot>/p<rho>/input.cgyro runners/input.cgyro; conda init; source ~/.bashrc; conda activate costsci-tools; python solvers/setup_cgyro.py; python checkouts/cgyro.py;
    image: gitlab-registry.nrp-nautilus.io/zclawrence/costsci-tools:latest
dataset:
  shot1_rho1:
    hparam:
      _shot: "171421.01825"
      _rho: "0.5"
  shot1_rho2:
    hparam:
      _shot: "171421.01825"
      _rho: "0.7"
  shot1_rho3:
    hparam:
      _shot: "171421.01825"
      _rho: "0.9"
  shot2_rho1:
    hparam:
      _shot: "171421.02175"
      _rho: "0.5"
  shot2_rho2:
    hparam:
      _shot: "171421.02175"
      _rho: "0.7"
  shot2_rho3:
    hparam:
      _shot: "171421.02175"
      _rho: "0.9"
  shot3_rho1:
    hparam:
      _shot: "171421.02450"
      _rho: "0.5"
  shot3_rho2:
    hparam:
      _shot: "171421.02450"
      _rho: "0.7"
  shot3_rho3:
    hparam:
      _shot: "171421.02450"
      _rho: "0.9"
  shot4_rho1:
    hparam:
      _shot: "171421.02850"
      _rho: "0.5"
  shot4_rho2:
    hparam:
      _shot: "171421.02850"
      _rho: "0.7"
  shot4_rho3:
    hparam:
      _shot: "171421.02850"
      _rho: "0.9"
  shot5_rho1:
    hparam:
      _shot: "171421.03400"
      _rho: "0.5"
  shot5_rho2:
    hparam:
      _shot: "171421.03400"
      _rho: "0.7"
  shot5_rho3:
    hparam:
      _shot: "171421.03400"
      _rho: "0.9"
  shot6_rho1:
    hparam:
      _shot: "171421.03600"
      _rho: "0.5"
  shot6_rho2:
    hparam:
      _shot: "171421.03600"
      _rho: "0.7"
  shot6_rho3:
    hparam:
      _shot: "171421.03600"
      _rho: "0.9"
  shot7_rho1:
    hparam:
      _shot: "171646.02310"
      _rho: "0.5"
  shot7_rho2:
    hparam:
      _shot: "171646.02310"
      _rho: "0.7"
  shot7_rho3:
    hparam:
      _shot: "171646.02310"
      _rho: "0.9"
  shot8_rho1:
    hparam:
      _shot: "171650.02310"
      _rho: "0.5"
  shot8_rho2:
    hparam:
      _shot: "171650.02310"
      _rho: "0.7"
  shot8_rho3:
    hparam:
      _shot: "171650.02310"
      _rho: "0.9"
  shot9_rho1:
    hparam:
      _shot: "180519.04250"
      _rho: "0.5"
  shot9_rho2:
    hparam:
      _shot: "180519.04250"
      _rho: "0.7"
  shot9_rho3:
    hparam:
      _shot: "180519.04250"
      _rho: "0.9"
  shot10_rho1:
    hparam:
      _shot: "180520.02150"
      _rho: "0.5"
  shot10_rho2:
    hparam:
      _shot: "180520.02150"
      _rho: "0.7"
  shot10_rho3:
    hparam:
      _shot: "180520.02150"
      _rho: "0.9"
  shot11_rho1:
    hparam:
      _shot: "180520.03300"
      _rho: "0.5"
  shot11_rho2:
    hparam:
      _shot: "180520.03300"
      _rho: "0.7"
  shot11_rho3:
    hparam:
      _shot: "180520.03300"
      _rho: "0.9"
  shot12_rho1:
    hparam:
      _shot: "180520.04700"
      _rho: "0.5"
  shot12_rho2:
    hparam:
      _shot: "180520.04700"
      _rho: "0.7"
  shot12_rho3:
    hparam:
      _shot: "180520.04700"
      _rho: "0.9"
  shot13_rho1:
    hparam:
      _shot: "180528.02300"
      _rho: "0.5"
  shot13_rho2:
    hparam:
      _shot: "180528.02300"
      _rho: "0.7"
  shot13_rho3:
    hparam:
      _shot: "180528.02300"
      _rho: "0.9"
  shot14_rho1:
    hparam:
      _shot: "180528.02800"
      _rho: "0.5"
  shot14_rho2:
    hparam:
      _shot: "180528.02800"
      _rho: "0.7"
  shot14_rho3:
    hparam:
      _shot: "180528.02800"
      _rho: "0.9"
  shot15_rho1:
    hparam:
      _shot: "180528.03300"
      _rho: "0.5"
  shot15_rho2:
    hparam:
      _shot: "180528.03300"
      _rho: "0.7"
  shot15_rho3:
    hparam:
      _shot: "180528.03300"
      _rho: "0.9"
  shot16_rho1:
    hparam:
      _shot: "180528.03700"
      _rho: "0.5"
  shot16_rho2:
    hparam:
      _shot: "180528.03700"
      _rho: "0.7"
  shot16_rho3:
    hparam:
      _shot: "180528.03700"
      _rho: "0.9"
  shot17_rho1:
    hparam:
      _shot: "180528.04100"
      _rho: "0.5"
  shot17_rho2:
    hparam:
      _shot: "180528.04100"
      _rho: "0.7"
  shot17_rho3:
    hparam:
      _shot: "180528.04100"
      _rho: "0.9"
  shot18_rho1:
    hparam:
      _shot: "180528.04550"
      _rho: "0.5"
  shot18_rho2:
    hparam:
      _shot: "180528.04550"
      _rho: "0.7"
  shot18_rho3:
    hparam:
      _shot: "180528.04550"
      _rho: "0.9"
  shot19_rho1:
    hparam:
      _shot: "180533.02300"
      _rho: "0.5"
  shot19_rho2:
    hparam:
      _shot: "180533.02300"
      _rho: "0.7"
  shot19_rho3:
    hparam:
      _shot: "180533.02300"
      _rho: "0.9"
  shot20_rho1:
    hparam:
      _shot: "180533.02800"
      _rho: "0.5"
  shot20_rho2:
    hparam:
      _shot: "180533.02800"
      _rho: "0.7"
  shot20_rho3:
    hparam:
      _shot: "180533.02800"
      _rho: "0.9"
  shot21_rho1:
    hparam:
      _shot: "180533.03300"
      _rho: "0.5"
  shot21_rho2:
    hparam:
      _shot: "180533.03300"
      _rho: "0.7"
  shot21_rho3:
    hparam:
      _shot: "180533.03300"
      _rho: "0.9"
run:
  # dataset: [shot1_rho1, shot1_rho2, shot1_rho3,
  #           shot2_rho1, shot2_rho2, shot2_rho3,
  #           shot3_rho1, shot3_rho2, shot3_rho3,
  #           shot4_rho1, shot4_rho2, shot4_rho3,
  #           shot5_rho1, shot5_rho2, shot5_rho3,
  #           shot6_rho1, shot6_rho2, shot6_rho3,
  #           shot7_rho1, shot7_rho2, shot7_rho3,
  #           shot8_rho1, shot8_rho2, shot8_rho3,
  #           shot9_rho1, shot9_rho2, shot9_rho3,
  #           shot10_rho1, shot10_rho2, shot10_rho3,
  #           shot11_rho1, shot11_rho2, shot11_rho3,
  #           shot12_rho1, shot12_rho2, shot12_rho3,
  #           shot13_rho1, shot13_rho2, shot13_rho3,
  #           shot14_rho1, shot14_rho2, shot14_rho3,
  #           shot15_rho1, shot15_rho2, shot15_rho3,
  #           shot16_rho1, shot16_rho2, shot16_rho3,
  #           shot17_rho1, shot17_rho2, shot17_rho3,
  #           shot18_rho1, shot18_rho2, shot18_rho3,
  #           shot19_rho1, shot19_rho2, shot19_rho3,
  #           shot20_rho1, shot20_rho2, shot20_rho3,
  #           shot21_rho1, shot21_rho2, shot21_rho3]
  dataset: [shot11_rho1, shot11_rho2, shot11_rho3,
            shot12_rho1, shot12_rho2, shot12_rho3,
            shot13_rho1, shot13_rho2, shot13_rho3,
            shot14_rho1, shot14_rho2, shot14_rho3,
            shot15_rho1, shot15_rho2, shot15_rho3,
            shot16_rho1, shot16_rho2, shot16_rho3,
            shot17_rho1, shot17_rho2, shot17_rho3,
            shot18_rho1, shot18_rho2, shot18_rho3,
            shot19_rho1, shot19_rho2, shot19_rho3,
            shot20_rho1, shot20_rho2, shot20_rho3,
            shot21_rho1, shot21_rho2, shot21_rho3]
  # dataset: [shot1_rho1, shot1_rho2, shot1_rho3,
  #           shot2_rho1, shot2_rho2, shot2_rho3,
  #           shot3_rho1, shot3_rho2, shot3_rho3,
  #           shot4_rho1, shot4_rho2, shot4_rho3,
  #           shot5_rho1, shot5_rho2, shot5_rho3,
  #           shot6_rho1, shot6_rho2, shot6_rho3,
  #           shot7_rho1, shot7_rho2, shot7_rho3,
  #           shot8_rho1, shot8_rho2, shot8_rho3,
  #           shot9_rho1, shot9_rho2, shot9_rho3,
  #           shot10_rho1, shot10_rho2, shot10_rho3]
  model: [checkout]

# Rhos = [
#   0.5
#   0.7
#   0.9
#]

# Shots = [
#   171421.01825
#   171421.02175
#   171421.02450
#   171421.02850
#   171421.03400
#   171421.03600
#   171646.02310
#   171650.02310
#   180519.04250
#   180520.02150
#   180520.03300
#   180520.04700
#   180528.02300
#   180528.02800
#   180528.03300
#   180528.03700
#   180528.04100
#   180528.04550
#   180533.02300
#   180533.02800
#   180533.03300
#]