import hydra
import sys
import os
import subprocess
import shutil
import glob

# import sdf_helper as sh
import h5py
import time
import numpy as np
import matplotlib.pyplot as plt
import json
from pathlib import Path
from pyrokinetics import Pyro

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

env = os.environ.copy()
env["PYTHONPATH"] = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))

@hydra.main(version_base=None, config_path="../run_configs/cgyro", config_name="p1")
def main(cfg):
    script_dir = os.path.normpath(os.path.dirname(__file__))  # directory of input.cgyro, change if move somewhere else
    gacode_dir = os.path.join(script_dir, "..", "solvers", "gacode") # WARNING: relies on script_dir being the directory of input.cgyro
    input_path = os.path.join(script_dir, "input.cgyro")
    backup_path = os.path.join(script_dir, "input.cgyro.backup")

    # Backup original input.cgyro for git cleanliness
    shutil.copy2(input_path, backup_path)
    try:
        updateInputCgyro(cfg, input_path)

        cmd = f". {gacode_dir}/shared/bin/gacode_setup && cgyro -i . && cgyro -e . -n 8"
        print(f'Running: {cmd}')
        start_time=time.time()

        env["GACODE_PLATFORM"] = "MINT_OPENMPI"
        env["GACODE_ROOT"] = gacode_dir
        env["OMPI_ALLOW_RUN_AS_ROOT"] = "1"
        env["OMPI_ALLOW_RUN_AS_ROOT_CONFIRM"] = "1"

        subprocess.run(cmd, shell=True, check=True, env=env, cwd=script_dir)
        end_time=time.time()
        run_time=end_time-start_time

        converged = False
        with open(os.path.join(script_dir, "out.cgyro.info"), "r") as f:
            lines = f.readlines()
            for i in range(len(lines) - 1, 0, -1):
                if "EXIT: (CGYRO) Linear converged" in lines[i]:
                    converged = True
                    break
            
        print(f"Elapsed time: {run_time:.4f} seconds")

        savePath = os.path.join(
            os.path.dirname(os.path.dirname(script_dir)),  # Go up two levels: runners -> costsci_tools -> SimulCost-Bench
            cfg.dump_dir
            + f"_n_radial_{cfg.n_radial}_n_theta_{cfg.n_theta}_freq_tol_{cfg.freq_tol}_delta_t_{cfg.delta_t}",
        )
        saveData(savePath)
        # Python dictionary representing the data
        metaData = {
            "cost": run_time,
            "converged": converged,
            "n_radial": cfg.n_radial,
            "n_theta": cfg.n_theta,
            "error_tol": cfg.error_tol,
            "freq_tol": cfg.freq_tol,
            "delta_t": cfg.delta_t
        }
        # Write the Python dictionary to a JSON file
        with open(os.path.join(savePath, "meta.json"), "w") as json_file:
            json.dump(metaData, json_file, indent=4)

        print("Simulation completed successfully!")
        # Restore original input.cgyro for git cleanliness
        if os.path.exists(backup_path):
            shutil.copy2(backup_path, input_path)
            os.remove(backup_path)

    finally:
        # Clean up temporary files generated by CGYRO
        script_dir = os.path.dirname(__file__)
        cleanup_patterns = ["bin.cgyro.*", "out.cgyro.*", "input.cgyro.gen"]

        for pattern in cleanup_patterns:
            for file_path in glob.glob(os.path.join(script_dir, pattern)):
                try:
                    os.remove(file_path)
                    print(f"Cleaned up: {os.path.basename(file_path)}")
                except OSError:
                    pass  # Ignore if file cannot be removed

        # Restore original input.cgyro for git cleanliness
        if os.path.exists(backup_path):
            shutil.copy2(backup_path, input_path)
            os.remove(backup_path)

def saveData(savePath):
    script_dir = os.path.dirname(__file__)
    input_file = os.path.join(script_dir, 'input.cgyro')
    os.makedirs(savePath, exist_ok=True)

    try:
        pyro = Pyro(gk_file=input_file)
        pyro.load_gk_output()
        pyro.base_pyro = pyro

        res = pyro.gk_output
        print(res)
        
        with h5py.File(os.path.join(savePath, "res.h5"), "w") as f:
            f.create_dataset("growth_rate", data=res['growth_rate'].to_numpy())
            f.create_dataset("mode_frequency", data=res['mode_frequency'].to_numpy())
            f.create_dataset("eigenvalues", data=res['eigenvalues'].to_numpy())
            f.create_dataset("particle", data=res['particle'].to_numpy())
            f.create_dataset("heat", data=res['heat'].to_numpy())
            f.create_dataset("momentum", data=res['momentum'].to_numpy())
    except ValueError:
        print('CGYRO was unable to start, and therefore did not converge.')

def updateInputCgyro(cfg, input_path):
    NON_CGYRO_CONFIG_KEYS = {
        "profile_model",
        "dump_dir",
        "verbose",
        "defaults"
    }
    with open(input_path, "r") as f:
        lines = f.readlines()
        for key, value in cfg.items():
            found_key = False
            for i in range(len(lines)):
                if key.upper().strip() == lines[i].split("=")[0].strip():
                    lines[i] = f"{key.upper()}={value}\n"
                    found_key = True
            if not found_key: # Append to end of lines
                if key.strip() in NON_CGYRO_CONFIG_KEYS:
                    continue
                lines.append(f"{key.upper()}={value}\n")

    with open(input_path, "w") as f:
        f.writelines(lines)

if __name__ == "__main__":
    main()
